---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.WWW_NAME}}"
spec:
  selector:
    matchLabels:
      name: "{{.WWW_NAME}}"
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: "{{.WWW_NAME}}"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: {{.WWW_NAME}}-proxy
        image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
        env:
        - name: PROXY_SERVICE_HOST
          value: "127.0.0.1"
        - name: PROXY_SERVICE_PORT
          value: "{{.WWW_PORT}}"
        - name: ENABLE_UUID_PARAM
          value: "FALSE"
        - name: LOG_FORMAT_NAME
          value: 'json'
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        - name: STATSD_METRICS
          value: "FALSE"
        - name: ADD_NGINX_LOCATION_CFG
          value: |
            client_max_body_size      50m;
        ports:
        - name: https
          containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
      - name: "{{.WWW_NAME}}"
        image: "{{.WWW_IMAGE}}:{{.WWW_TAG}}"
        imagePullPolicy: Always
        env:
        - name: WWW_NAME
          value: "{{.WWW_NAME}}"
        - name: WWW_PORT
          value: "{{.WWW_PORT}}"
        - name: WWW_UI_ENVIRONMENT
          value: "{{.WWW_UI_ENVIRONMENT}}"
        - name: WWW_UI_VERSION
          value: "{{.WWW_UI_VERSION}}"
        - name: WWW_STORAGE_KEY
          value: "{{.WWW_STORAGE_KEY}}"
        - name: WWW_KEYCLOAK_CLIENT_ID
          value: "{{.WWW_KEYCLOAK_CLIENT_ID}}"
        - name: WWW_KEYCLOAK_ACCESS_ROLE
          value: "{{.WWW_KEYCLOAK_ACCESS_ROLE}}"
        - name: KEYCLOAK_REALM
          value: "{{.KEYCLOAK_REALM}}"
        - name: KEYCLOAK_URI
          value: "{{.KEYCLOAK_PROTOCOL}}{{.KEYCLOAK_URL}}"
        - name: API_REF_URI
          value: "{{.API_REF_PROTOCOL}}{{.API_REF_URL}}"
        - name: API_COP_URI
          value: "{{.API_COP_PROTOCOL}}{{.API_COP_URL}}"
        - name: ENGINE_URI
          value: "{{.ENGINE_PROTOCOL}}{{.ENGINE_URL}}"
        - name: REPORT_URI
          value: "{{.REPORT_PROTOCOL}}{{.REPORT_URL}}"
        - name: API_FORM_URI
          value: "{{.API_FORM_PROTOCOL}}{{.API_FORM_URL}}"
        - name: API_ATTACHMENT_URI
          value: "{{.API_ATTACHMENT_PROTOCOL}}{{.API_ATTACHMENT_URL}}"
        - name: ANALYTICS_URL
          value: "{{.ANALYTICS_URL}}"
        - name: ANALYTICS_SITE_ID
          value: "{{.ANALYTICS_SITE_ID}}"
        - name: BROWSER_VERSIONS
          value: "{{.BROWSER_VERSIONS}}"
        - name: DETECT_BROWSER
          value: "{{.DETECT_BROWSER}}"
        securityContext:
          runAsNonRoot: true
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{.WWW_PORT}}
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{.WWW_PORT}}
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
      volumes:
      - name: certs
        secret:
          secretName: "{{.WWW_NAME}}-pod-cmio"
