---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.WWW_NAME}}
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-send-timeout: "3600"
    ingress.kubernetes.io/proxy-read-timeout: "3600"
#    ingress.kubernetes.io/whitelist-source-range: {{.WHITELIST}}
    stable.k8s.psg.io/kcm.provider: http
spec:
  rules:
  - host: {{.WWW_URL}}
    http:
      paths:
      - backend:
          serviceName: {{.WWW_NAME}}
          servicePort: 10443
        path: /
  tls:
  - hosts:
    - {{.WWW_URL}}
    secretName: {{.WWW_URL}}-tls
